---
# Frontend Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: oralie-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: oralie-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_DEBUG_HYDRATION
          value: "1"
        - name: NEXT_PUBLIC_API_URL
          value: "http://api.oralie.local"
        - name: NEXT_PUBLIC_URL
          value: "http://oralie.local"
        - name: NEXTAUTH_SECRET
          valueFrom:
            configMapKeyRef:
              name: oralie-config
              key: NEXTAUTH_SECRET
        - name: KEYCLOAK_URL
          value: "http://keycloak.oralie.local"
        - name: KEYCLOAK_DOMAIN
          value: "http://keycloak.oralie.local/realms/oralie"
        - name: KEYCLOAK_END_SESSION_URL
          value: "http://keycloak.oralie.local/realms/oralie/protocol/openid-connect/logout"
        - name: KEYCLOAK_REFRESH_TOKEN_URL
          value: "http://keycloak.oralie.local/realms/oralie/protocol/openid-connect/token"
        - name: KEYCLOAK_STORE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: oralie-config
              key: KEYCLOAK_STORE_CLIENT_ID
        - name: KEYCLOAK_STORE_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: oralie-config
              key: KEYCLOAK_STORE_CLIENT_SECRET
        - name: URL_AWS_S3
          value: "oralie-bucket.s3.ap-southeast-1.amazonaws.com"
        - name: URL_TT
          value: "ttcenter.com.vn"
        - name: URL_PICTURE
          value: "lh3.googleusercontent.com"
        - name: NEXTAUTH_URL
          value: "http://oralie.local"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: oralie-config
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET 
          valueFrom:
            configMapKeyRef:
              name: oralie-config
              key: GOOGLE_CLIENT_SECRET
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: oralie-system
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000 