---
# Gateway Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  namespace: oralie-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: vietquoc2408/gatewayserver-oralie:latest
        ports:
        - containerPort: 8072
        env:
        - name: SPRING_APPLICATION_NAME
          value: "gatewayserver"
        - name: OTEL_SERVICE_NAME
          value: "gatewayserver"
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://configserver:8071/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eurekaserver:8070/eureka/"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          value: "http://keycloak:8080/realms/oralie/protocol/openid-connect/certs"
        - name: SPRING_DATA_REDIS_CONNECT-TIMEOUT
          value: "2s"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_TIMEOUT
          value: "1s"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/etc/opentelemetry-javaagent.jar"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo:4317"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8072
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8072
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 800Mi
        volumeMounts:
        - name: opentelemetry-javaagent
          mountPath: /etc/opentelemetry-javaagent.jar
          subPath: opentelemetry-javaagent.jar
      volumes:
      - name: opentelemetry-javaagent
        emptyDir: {}
      initContainers:
      - name: download-otel-agent
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - curl -L -o /agent/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
        volumeMounts:
        - name: opentelemetry-javaagent
          mountPath: /agent
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
  namespace: oralie-system
spec:
  selector:
    app: gatewayserver
  ports:
  - port: 8072
    targetPort: 8072 