apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: oralie-system
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS accounts_db;
    CREATE DATABASE IF NOT EXISTS products_db;
    CREATE DATABASE IF NOT EXISTS carts_db;
    CREATE DATABASE IF NOT EXISTS orders_db;
    CREATE DATABASE IF NOT EXISTS rates_db;
    CREATE DATABASE IF NOT EXISTS inventory_db; 