---
# Tempo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: oralie-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        args: ["-config.file", "/etc/tempo-config.yml"]
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 4317
          name: otlp-grpc
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo-config.yml
          subPath: tempo-config.yml
        - name: tempo-data
          mountPath: /tmp/tempo
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
      - name: tempo-data
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: oralie-system
data:
  tempo-config.yml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: oralie-system
spec:
  selector:
    app: tempo
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: otlp-grpc
    port: 4317
    targetPort: 4317 